[[structured_sandbox]]
== Structured sandbox

These sites, which are typically geared towards learning a specific language or tool, provides a guided introduction using a live code sandbox.  For example, you're asked to declare a variable of a certain type, compute a certain value, or perform some task on a data structure (like reverse an array).  Typically, these steps are executed using some sort of testing suite to confirm that the user performed the task.

* Strengths
** Highly interactive.  A user usually cannot progress until they've successfully completed the coding step.
** Granularly structured.  The courses are usually very well structured, based around tasks or specific excercises.
** Game-ifable.  It's very simple to award badges and whatnot based on completion. 
* Weaknesses
** Rigid.  These tend towards lowest common demoninator topics that can only be expressed in simple, step-by-step tasks
** Complex to develop.  The test suites require a specialized author who can write the tests.

Examples include:

* Codecademy 
* Codeschool (Rails for Zombies, Try Objective-C, etc)
* Various "try" sites

[[structured_sandbox_shoutout]]
[role="shoutout"]
.Have a suggestion or comment?
****
Post suggestions or comments here.
****